### ISSUE TITLE
alghoritm_FCFS.h  Warning : "address of local variable ‘attesaCoda’ returned [-Wreturn-local-addr]"

### ISSUE THREAD

**Issue by sabatinipaolo** [6Bello/operative_system#2]
Lo so, ci dicono che i Warning non bloccano la compilazione e il programma funziona lo stesso ...
Ma ignorarli si potrebbe dimostrare una dannazione!
Nel caso: 
sotto windows funziona, sotto Linux in esecuzione da "segmentation fault" : 
![immagine](https://user-images.githubusercontent.com/113015247/232339799-f39b6d43-1228-4b06-86b6-aa0869c7c988.png)

Il problema sta in : 

``` cpp
int *trovaAttesaSingola(processo processi[], int processiLength){
	int attesaCoda[processiLength];
	attesaCoda[0] = 0;
	int tempoDiEsecuzioneTotale = 0;
	for (int i=1; i<processiLength; i++){
		tempoDiEsecuzioneTotale += processi[i-1].tempoDiEsecuzione;
		attesaCoda[i] = tempoDiEsecuzioneTotale-processi[i].istanteDiArrivo;
	}
	return attesaCoda;  // QUI IL PROBLEMA !!
}
```

la variabile attesaCoda è una variabile locale che _cessa di vivere_  nel suo _scopo_ ( nel caso il corpo della funzione), quindi nel nostro caso il compilatore ci avverte che i suoi valori _potrebbero non esistere più_ dopo l'esecuzione della funzione (dipende da come il sistema operativo gestisce la memoria associata ai processi..).

Ora nel caso sia un tipo primitivo non ci sono problemi, se fosse un int viene restituito il suo unico valore e la variabile può _morire in pace_.
Ma gli array non sono da considerare come un entità unica (in C ) di tutti i suoi elementi ed ecco perché non possiamo ritornare un array da una funzione.

 di fatto:
    -Un array è implicitamente convertito ad un puntatore al primo elemento;
    -Un puntatore condivide con gli array qualche costrutto sintattico (esempio se ` p[] ` )

Questo ci permette di risolvere certe questioni...
Ma i puntatori sono per certi versi molto pericolosi, ci permettono (quando non interviene il sistema operativo) di accedere a zonzo per la memoria e questo lo capisci da te che pericoli possono crearsi!!
Usare solo se veramente necessari avendo piena consapevolezzza di quel che si fa !!

**Comment by 6Bello** [comment]
quindi è proprio da escludere il far ritornare un array da una funzione? Dovrei per forza creare un void in cui passare l'indirizzo di memoria dell'array?

**Comment by sabatinipaolo** [comment]
yes ... stavo per sottomerti la soluzione ...

**Comment by sabatinipaolo** [comment]
Lo so "io so' forte e uso i puntatori!!" 
Ma i oggi i progammatori forti non sono quelli che usano robbe complicate quando (a parità di performance) cose più semplici e più facili da comprendere fanno lo stesso !!
